[package]
name = "toygit"
version = "0.1.0"
authors = ["Benjamin Levy <blevy@protonmail.com>"]
edition = "2018"

[dependencies]
libtoygit = { path = "../libtoygit" }
clap = "2.33.0"
string-error = "0.1.0"
env_logger = "0.6.2"
